version: 2
jobs:
  build:
    docker:
      - image: rust:1.36
    steps:
      - checkout
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ .Branch }}
            - v2-cargo-cache-{{ arch }}

      # Show versions
      - run: rustc --version && cargo --version

      # Build
      - run: cargo build
      - run: cargo build --features logging

      # Run tests
      - run: cargo test

      - save_cache:
          key: v2-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v2-cargo-cache-{{ arch }}
          paths:
            - target
            - /usr/local/cargo
